# fly.toml app configuration file generated for divine-forest-3796 on 2023-11-02T16:55:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "divine-forest-3796"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
